### ISSUE TITLE
You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

### ISSUE THREAD

**Issue by gustawdaniel** [dhhb/vue-base64-file-upload#6]
I have error when use vue-cli3.

**Comment by emjayess** [comment]
Create a `vue.config.js` file in the project root directory:
> `$ touch vue.config.js`

And add this directive to it:
```js
module.exports = {
  runtimeCompiler: true
}
```

Then run `npm run serve` again.

---
### Reference: 
https://cli.vuejs.org/config/#runtimecompiler

**Comment by gustawdaniel** [comment]
Thank you @emjayess
